#!/usr/bin/env python3
"""Guided bootstrap for the operator/infra config layer.

Agentic Ops config has three layers (see docs/roadmap for the full picture):

1. Bootstrap / infra (this script) — the minimum needed to cold-start and
   reach the workflow repo: which repo/ref/PAT to sync, the age identity used
   to decrypt its secrets, and the model gateway API key. Operator-owned,
   generated, never committed.
2. Instance config — the workflow repo's own `platform-config.yaml` (message
   bus, mcps, connectors, memory banks, model profiles, workflow secrets).
   Read only after the repo has been fetched using layer 1.
3. Workflow packages — `workflows/`, `skills/`, `hooks/`, custom `mcps/`,
   `connectors/` inside the workflow repo.

This script only produces layer 1. It never reads or writes the workflow
repo's `platform-config.yaml`.

Usage:
    python scripts/bootstrap.py                       # interactive
    python scripts/bootstrap.py --non-interactive ...  # CI-friendly

Every prompt has a corresponding --flag and environment variable override so
the same script can run non-interactively in pipelines.
"""

from __future__ import annotations

import argparse
import getpass
import os
import stat
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

VALID_TARGETS = ("compose", "kubernetes", "gcp")
VALID_SOURCES = ("remote", "local")


@dataclass(frozen=True)
class BootstrapConfig:
    target: str
    source: str
    repo_url: str = ""
    repo_ref: str = ""
    repo_pat: str = ""
    local_path: str = ""
    age_identity: str = ""
    model_gateway_api_key: str = ""

    def validate(self) -> None:
        if self.target not in VALID_TARGETS:
            raise ValueError(f"--target must be one of {VALID_TARGETS}, got {self.target!r}")
        if self.source not in VALID_SOURCES:
            raise ValueError(f"--source must be one of {VALID_SOURCES}, got {self.source!r}")
        if self.source == "remote" and self.target == "compose":
            raise ValueError(
                "compose deployments bind-mount a local workflow-repo checkout today; "
                "use --source local for --target compose, or --target kubernetes/gcp for git-based sync"
            )
        if self.source == "remote" and not self.repo_url:
            raise ValueError("--repo-url is required for --source remote")
        if self.source == "local" and not self.local_path:
            raise ValueError("--local-path is required for --source local")
        if not self.age_identity:
            raise ValueError("--age-identity is required")
        if not self.model_gateway_api_key:
            raise ValueError("--model-gateway-api-key is required")


def normalize_age_identity(value: str) -> str:
    """Return the AGE_IDENTITY value in the runtime's expected form.

    Accepts a raw armored key, an existing `file:`-prefixed path, or a bare
    filesystem path — the latter is rewritten to `file:<path>` to match the
    convention services already use (see shared/lib/config.py).
    """
    value = value.strip()
    if not value or value.startswith("file:") or value.startswith("AGE-SECRET-KEY-"):
        return value
    if Path(value).expanduser().exists():
        return f"file:{Path(value).expanduser()}"
    return value


def build_bootstrap_env(config: BootstrapConfig) -> dict[str, str]:
    """Return the bootstrap KEY=VALUE env mapping for the chosen target/source."""
    env: dict[str, str] = {
        "AGE_IDENTITY": normalize_age_identity(config.age_identity),
        "MODEL_GATEWAY_API_KEY": config.model_gateway_api_key,
    }
    if config.source == "remote":
        env["WORKFLOW_REPO_URL"] = config.repo_url
        env["WORKFLOW_REPO_REF"] = config.repo_ref
        if config.repo_pat:
            env["WORKFLOW_REPO_PAT"] = config.repo_pat
    else:
        local_path = str(Path(config.local_path).expanduser())
        if config.target == "compose":
            env["HOST_WORKFLOW_REPO_PATH"] = local_path
            env["HOST_PLATFORM_CONFIG_FILE"] = str(Path(local_path) / "platform-config.yaml")
        else:
            env["WORKFLOW_REPO_PATHS"] = local_path
    return env


def _shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def render_compose_env(env: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/bootstrap.py -- do not commit.",
        "# Operator/bootstrap secrets only. Instance config lives in the workflow",
        "# repo's platform-config.yaml.",
        *(f"{key}={value}" for key, value in env.items()),
    ]
    return "\n".join(lines) + "\n"


def render_k8s_secret_script(
    env: dict[str, str],
    *,
    secret_name: str = "agentic-ops-bootstrap",  # noqa: S107 - resource name, not a credential
    namespace: str = "default",
) -> str:
    literals = " \\\n  ".join(f"--from-literal={key}={_shell_quote(value)}" for key, value in env.items())
    return (
        "#!/usr/bin/env bash\n"
        "# Generated by scripts/bootstrap.py -- do not commit. Run once per cluster/namespace.\n"
        "set -euo pipefail\n\n"
        f"kubectl create secret generic {secret_name} \\\n"
        f"  --namespace {namespace} \\\n"
        f"  {literals} \\\n"
        "  --dry-run=client -o yaml | kubectl apply -f -\n"
    )


def render_gcp_secrets_script(env: dict[str, str], *, project: str = "") -> str:
    project_flag = f" --project={project}" if project else ""
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by scripts/bootstrap.py -- do not commit. Run once per GCP project.",
        "set -euo pipefail",
        "",
    ]
    for key, value in env.items():
        quoted = _shell_quote(value)
        lines.append(
            f"printf '%s' {quoted} | gcloud secrets create {key}{project_flag} "
            f"--data-file=- --replication-policy=automatic 2>/dev/null || "
            f"printf '%s' {quoted} | gcloud secrets versions add {key}{project_flag} --data-file=-"
        )
    return "\n".join(lines) + "\n"


def write_artifact(config: BootstrapConfig, *, output_dir: Path = REPO_ROOT) -> Path:
    env = build_bootstrap_env(config)
    if config.target == "compose":
        path = output_dir / "compose.env"
        path.write_text(render_compose_env(env), encoding="utf-8")
        return path

    path = output_dir / "dist" / "bootstrap" / ("k8s-secret.sh" if config.target == "kubernetes" else "gcp-secrets.sh")
    path.parent.mkdir(parents=True, exist_ok=True)
    content = render_k8s_secret_script(env) if config.target == "kubernetes" else render_gcp_secrets_script(env)
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IEXEC)
    return path


def _prompt(label: str, *, default: str = "", secret: bool = False) -> str:
    reader = getpass.getpass if secret else input
    suffix = f" [{default}]" if default and not secret else ""
    value = reader(f"{label}{suffix}: ").strip()
    return value or default


def gather_config_interactively(args: argparse.Namespace) -> BootstrapConfig:
    target = args.target or _prompt("Deployment target (compose/kubernetes/gcp)", default="compose")
    default_source = "local" if target == "compose" else "remote"
    source = args.source or _prompt("Workflow source (remote/local)", default=default_source)

    repo_url, repo_ref, repo_pat, local_path = args.repo_url, args.repo_ref, args.repo_pat, args.local_path
    if source == "remote" and not repo_url:
        repo_url = _prompt("Workflow repo URL")
        repo_ref = repo_ref or _prompt("Workflow repo ref (tag or SHA)", default="main")
        repo_pat = repo_pat or _prompt("Workflow repo PAT (blank for public repos)", secret=True)
    elif source == "local" and not local_path:
        local_path = _prompt("Local workflow-repo checkout path")

    age_identity = args.age_identity or _prompt("AGE identity (inline key or path to key.txt)", secret=True)
    model_gateway_api_key = args.model_gateway_api_key or _prompt("Model gateway API key", secret=True)

    return BootstrapConfig(
        target=target,
        source=source,
        repo_url=repo_url or "",
        repo_ref=repo_ref or "",
        repo_pat=repo_pat or "",
        local_path=local_path or "",
        age_identity=age_identity or "",
        model_gateway_api_key=model_gateway_api_key or "",
    )


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--target", choices=VALID_TARGETS, default=os.environ.get("BOOTSTRAP_TARGET", ""))
    parser.add_argument("--source", choices=VALID_SOURCES, default=os.environ.get("BOOTSTRAP_SOURCE", ""))
    parser.add_argument("--repo-url", default=os.environ.get("WORKFLOW_REPO_URL", ""))
    parser.add_argument("--repo-ref", default=os.environ.get("WORKFLOW_REPO_REF", "main"))
    parser.add_argument("--repo-pat", default=os.environ.get("WORKFLOW_REPO_PAT", ""))
    parser.add_argument("--local-path", default=os.environ.get("WORKFLOW_REPO_LOCAL_CHECKOUT", ""))
    parser.add_argument("--age-identity", default=os.environ.get("AGE_IDENTITY", ""))
    parser.add_argument("--model-gateway-api-key", default=os.environ.get("MODEL_GATEWAY_API_KEY", ""))
    parser.add_argument("--non-interactive", action="store_true", help="Fail on missing values instead of prompting")
    parser.add_argument("--output-dir", type=Path, default=REPO_ROOT, help="Where to write the generated artifact")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    if args.non_interactive:
        config = BootstrapConfig(
            target=args.target,
            source=args.source,
            repo_url=args.repo_url,
            repo_ref=args.repo_ref,
            repo_pat=args.repo_pat,
            local_path=args.local_path,
            age_identity=args.age_identity,
            model_gateway_api_key=args.model_gateway_api_key,
        )
    else:
        config = gather_config_interactively(args)

    try:
        config.validate()
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    path = write_artifact(config, output_dir=args.output_dir)
    print(f"Wrote bootstrap artifact: {path}")
    if config.target == "compose":
        print("Run: docker compose -f deploy/docker-compose.yml --env-file compose.env up -d")
    else:
        print(f"Run {path} to create the {config.target} secret, then deploy as usual.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
