"""Unit tests for the guided operator bootstrap script (scripts/bootstrap.py)."""

from __future__ import annotations

from pathlib import Path

import pytest

from scripts.bootstrap import (
    BootstrapConfig,
    build_bootstrap_env,
    main,
    normalize_age_identity,
    render_compose_env,
    render_gcp_secrets_script,
    render_k8s_secret_script,
    write_artifact,
)

pytestmark = pytest.mark.unit


def _remote_config(**overrides) -> BootstrapConfig:
    base = {
        "target": "kubernetes",
        "source": "remote",
        "repo_url": "https://github.com/acme/workflows.git",
        "repo_ref": "v1.2.3",
        "repo_pat": "ghp_token",
        "age_identity": "AGE-SECRET-KEY-1EXAMPLE",
        "model_gateway_api_key": "sk-model-key",
    }
    base.update(overrides)
    return BootstrapConfig(**base)


def _local_config(**overrides) -> BootstrapConfig:
    base = {
        "target": "compose",
        "source": "local",
        "local_path": "/home/op/corp-workflows",
        "age_identity": "AGE-SECRET-KEY-1EXAMPLE",
        "model_gateway_api_key": "sk-model-key",
    }
    base.update(overrides)
    return BootstrapConfig(**base)


# ── Validation ──────────────────────────────────────────────────────


def test_validate_rejects_remote_source_for_compose_target():
    config = _remote_config(target="compose")
    with pytest.raises(ValueError, match="bind-mount a local workflow-repo checkout"):
        config.validate()


def test_validate_requires_repo_url_for_remote_source():
    config = _remote_config(repo_url="")
    with pytest.raises(ValueError, match="--repo-url is required"):
        config.validate()


def test_validate_requires_local_path_for_local_source():
    config = _local_config(local_path="")
    with pytest.raises(ValueError, match="--local-path is required"):
        config.validate()


def test_validate_requires_age_identity_and_model_key():
    with pytest.raises(ValueError, match="--age-identity is required"):
        _remote_config(age_identity="").validate()
    with pytest.raises(ValueError, match="--model-gateway-api-key is required"):
        _remote_config(model_gateway_api_key="").validate()


def test_validate_accepts_valid_remote_kubernetes_config():
    _remote_config().validate()  # does not raise


def test_validate_accepts_valid_local_compose_config():
    _local_config().validate()  # does not raise


# ── normalize_age_identity ──────────────────────────────────────────


def test_normalize_age_identity_passes_through_raw_key():
    assert normalize_age_identity("AGE-SECRET-KEY-1EXAMPLE") == "AGE-SECRET-KEY-1EXAMPLE"


def test_normalize_age_identity_passes_through_existing_file_prefix():
    assert normalize_age_identity("file:/etc/agentic-ops/key.txt") == "file:/etc/agentic-ops/key.txt"


def test_normalize_age_identity_wraps_existing_path(tmp_path: Path):
    key_file = tmp_path / "key.txt"
    key_file.write_text("AGE-SECRET-KEY-1EXAMPLE\n", encoding="utf-8")
    assert normalize_age_identity(str(key_file)) == f"file:{key_file}"


def test_normalize_age_identity_leaves_nonexistent_path_as_raw_value():
    assert normalize_age_identity("not-a-real-path-or-key") == "not-a-real-path-or-key"


# ── build_bootstrap_env ──────────────────────────────────────────────


def test_build_bootstrap_env_remote_source_includes_repo_pointer():
    env = build_bootstrap_env(_remote_config())
    assert env["WORKFLOW_REPO_URL"] == "https://github.com/acme/workflows.git"
    assert env["WORKFLOW_REPO_REF"] == "v1.2.3"
    assert env["WORKFLOW_REPO_PAT"] == "ghp_token"
    assert env["AGE_IDENTITY"] == "AGE-SECRET-KEY-1EXAMPLE"
    assert env["MODEL_GATEWAY_API_KEY"] == "sk-model-key"


def test_build_bootstrap_env_remote_source_omits_pat_when_blank():
    env = build_bootstrap_env(_remote_config(repo_pat=""))
    assert "WORKFLOW_REPO_PAT" not in env


def test_build_bootstrap_env_local_compose_sets_host_bind_mount_vars():
    env = build_bootstrap_env(_local_config())
    assert env["HOST_WORKFLOW_REPO_PATH"] == "/home/op/corp-workflows"
    assert env["HOST_PLATFORM_CONFIG_FILE"] == "/home/op/corp-workflows/platform-config.yaml"
    assert "WORKFLOW_REPO_PATHS" not in env


def test_build_bootstrap_env_local_kubernetes_sets_workflow_repo_paths():
    env = build_bootstrap_env(_local_config(target="kubernetes"))
    assert env["WORKFLOW_REPO_PATHS"] == "/home/op/corp-workflows"
    assert "HOST_WORKFLOW_REPO_PATH" not in env


# ── Render functions ──────────────────────────────────────────────────


def test_render_compose_env_shape():
    content = render_compose_env({"AGE_IDENTITY": "abc", "MODEL_GATEWAY_API_KEY": "xyz"})
    assert "AGE_IDENTITY=abc" in content
    assert "MODEL_GATEWAY_API_KEY=xyz" in content
    assert content.startswith("# Generated by scripts/bootstrap.py")


def test_render_k8s_secret_script_contains_kubectl_apply():
    content = render_k8s_secret_script({"AGE_IDENTITY": "abc"}, secret_name="my-secret", namespace="ops")
    assert "kubectl create secret generic my-secret" in content
    assert "--namespace ops" in content
    assert "--from-literal=AGE_IDENTITY='abc'" in content
    assert "kubectl apply -f -" in content


def test_render_gcp_secrets_script_contains_gcloud_commands():
    content = render_gcp_secrets_script({"AGE_IDENTITY": "abc"}, project="my-proj")
    assert "gcloud secrets create AGE_IDENTITY --project=my-proj" in content
    assert "gcloud secrets versions add AGE_IDENTITY --project=my-proj" in content


def test_render_scripts_quote_values_with_special_characters():
    content = render_k8s_secret_script({"MODEL_GATEWAY_API_KEY": "it's a 'secret'"})
    assert "it'\\''s a '\\''secret'\\''" in content


# ── write_artifact ──────────────────────────────────────────────────


def test_write_artifact_compose_target_writes_compose_env(tmp_path: Path):
    path = write_artifact(_local_config(), output_dir=tmp_path)
    assert path == tmp_path / "compose.env"
    assert path.exists()
    assert "HOST_WORKFLOW_REPO_PATH=" in path.read_text(encoding="utf-8")


def test_write_artifact_kubernetes_target_writes_executable_script(tmp_path: Path):
    path = write_artifact(_remote_config(), output_dir=tmp_path)
    assert path == tmp_path / "dist" / "bootstrap" / "k8s-secret.sh"
    assert path.exists()
    assert path.stat().st_mode & 0o111  # executable bit set


def test_write_artifact_gcp_target_writes_executable_script(tmp_path: Path):
    path = write_artifact(_remote_config(target="gcp"), output_dir=tmp_path)
    assert path == tmp_path / "dist" / "bootstrap" / "gcp-secrets.sh"
    assert path.exists()
    assert path.stat().st_mode & 0o111


# ── main() (non-interactive CLI) ──────────────────────────────────────


def test_main_non_interactive_writes_compose_env(tmp_path: Path, capsys):
    exit_code = main(
        [
            "--non-interactive",
            "--target",
            "compose",
            "--source",
            "local",
            "--local-path",
            "/home/op/corp-workflows",
            "--age-identity",
            "AGE-SECRET-KEY-1EXAMPLE",
            "--model-gateway-api-key",
            "sk-model-key",
            "--output-dir",
            str(tmp_path),
        ]
    )
    assert exit_code == 0
    assert (tmp_path / "compose.env").exists()
    assert "docker compose" in capsys.readouterr().out


def test_main_non_interactive_missing_required_value_returns_error(tmp_path: Path, capsys):
    exit_code = main(
        [
            "--non-interactive",
            "--target",
            "kubernetes",
            "--source",
            "remote",
            "--age-identity",
            "AGE-SECRET-KEY-1EXAMPLE",
            "--model-gateway-api-key",
            "sk-model-key",
            "--output-dir",
            str(tmp_path),
        ]
    )
    assert exit_code == 1
    assert "--repo-url is required" in capsys.readouterr().err


def test_main_non_interactive_rejects_remote_compose_combo(tmp_path: Path, capsys):
    exit_code = main(
        [
            "--non-interactive",
            "--target",
            "compose",
            "--source",
            "remote",
            "--repo-url",
            "https://github.com/acme/workflows.git",
            "--age-identity",
            "AGE-SECRET-KEY-1EXAMPLE",
            "--model-gateway-api-key",
            "sk-model-key",
            "--output-dir",
            str(tmp_path),
        ]
    )
    assert exit_code == 1
    assert "bind-mount a local workflow-repo checkout" in capsys.readouterr().err
